trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - features/**

resources:
- repo: self

stages:
- template: templates/build-push-image/templates-build-push-images.yml

- template: templates/deploy-to-app-service/templates-to-deploy-appservice.yml
