resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4d662b40-2626-4ab9-bee0-8f2a3e6dac17'
  imageRepository: 'springpetclinic'
  containerRegistry: 'gsspringbootcr.azurecr.io'
  registryName: 'gsSpringBootCR'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  webAppName: spring-petclinic

  azureSubscription: 'Azure subscription 1(4)(63e6a2d7-6014-442b-8af9-f1ca1ec71b0e)'

  # Docker information
  dockerUsername: gsSpringBootCR
  dockerPassword: 9Sb9L4www+ZPz9bdLEQpmO436X2tQ6TQJJXvvVHFG4+ACRCMHdtQ gsspringbootcr.azurecr.io
  dockerContainerName: spring-petclinic-app

stages:
- template: templates/build-push-image/templates-build-push-images.yml

- stage: Deploy
  displayName: Stage to deploy
  jobs:
    - deployment: VMDeploy
      displayName: Deploy to VM
      environment:
        name: ContosoDeploy
        resourceName: DESKTOP-BUGKGO7
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Bash@3
                inputs:
                  targetType: inline
                  script: |           
                    docker login -u $(dockerUsername) -p $(dockerPassword)
                    # Check if container exists
                    if docker ps -a | grep $(dockerContainerName); then
                      # Remove the container
                      docker rm -f $(dockerContainerName)
                    fi
                    docker pull $(containerRegistry)/springpetclinic:100
                    docker run -d --name $(dockerContainerName) $(containerRegistry)/springpetclinic:$(tag)
              - task: Docker@2
                inputs:
                  command: login
                  containerRegistry: $(registryName)
              - task: Docker@2
                displayName: Start docker container
                inputs:
                  command: start
                  containerRegistry: $(registryName)
                  container: $(dockerContainerName)
              - task: AzureWebAppContainer@1
                displayName: Deploy to Azure Web App for Containers
                inputs:
                  azureSubscription: $(azureSubscription)
                  appName: '$(webAppName)'
                  containers: '$(imageRepository):$(tag)'
