stages:
  - stage: Deploy
    displayName: Stage to Deploy
    variables:
      # Docker Container Registry information
      imageRepository: 'springpetclinic'
      containerRegistry: 'gsspringbootcr.azurecr.io'
      registryName: 'gsSpringBootCR'
      tag: '$(Build.BuildId)'

      # Docker information
      dockerUsername: gsSpringBootCR
      dockerPassword: 9Sb9L4www+ZPz9bdLEQpmO436X2tQ6TQJJXvvVHFG4+ACRCMHdtQ gsspringbootcr.azurecr.io
      dockerContainerName: spring-petclinic-app
    jobs:
      - job: Deploy
        displayName: Deploy to App Service
        steps:
        - task: AzureWebAppContainer@1
          displayName: Deploy to Azure Web App for Containers
          inputs:
            azureSubscription: 'Azure subscription 1(4)(63e6a2d7-6014-442b-8af9-f1ca1ec71b0e)'
            appName: $(webAppName)
            containers: $(imageRepository):$(tag)
