stages:
  - stage: Deploy
    displayName: Stage to Deploy
    variables:
      # Docker Container Registry information
      imageRepository: 'springpetclinic'
      containerRegistry: 'springpetcliniccr.azurecr.io'
      registryName: 'springpetclinicCR'
      tag: '$(Build.BuildId)'

      webAppName: 'spring-petclinic'

      # Docker information
      dockerUsername: springpetcliniccr.azurecr.io
      dockerPassword: 6RxVIkb29Mpeo9xpPlHvpPdFxZovRHFZWOQH+SISun+ACRCdfupt
      dockerContainerName: spring-petclinic-app
    jobs:
      - job: Deploy
        displayName: Deploy to App Service
        steps:
        - task: AzureWebAppContainer@1
          displayName: Deploy to Azure Web App for Containers
          inputs:
            azureSubscription: 'Azure subscription 1(4)(63e6a2d7-6014-442b-8af9-f1ca1ec71b0e)'
            appName: $(webAppName)
            containers: $(imageRepository):$(tag)
