stages:
- stage:
  displayName: Build and Push stage
  variable:
    vmImageName: 'ubuntu-latest'
  jobs:
    - job: Build
      pool:
        vmImage: $(vmImageName)
      displayName: Build and Push
      steps:
      - task: Docker@2
        displayName: Build and Push an image to CR
        inputs:
          command: buildAndPush
          repository: $(imageRepository)

          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
      