stages:
- stage:
  displayName: Build and Push stage
  variables:
    vmImageName: 'ubuntu-latest'

    dockerRegistryServiceConnection: '4d662b40-2626-4ab9-bee0-8f2a3e6dac17'
  jobs:
    - job: Build
      pool:
        vmImage: $(vmImageName)
      displayName: Build and Push
      steps:
      - task: Docker@2
        displayName: Build and Push an image to CR
        inputs:
          command: buildAndPush
          repository: $(imageRepository)

          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
